### ISSUE TITLE
UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'

### ISSUE THREAD

**Issue by shibababa** [mattyamonaca/layerdivider#50]
I can't resolve this error.
`UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'`
Also, I finally get an error like this too.
```
raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```
Also, when I run run_gui.ps1, I get an error like this.
`ModuleNotFoundError: No module named 'gradio'`

I checked with "pip list" and found that "gradio" is installed correctly.

Therefore, I have no choice but to run "python.exe demo.py" from the command prompt.

**Comment by shibababa** [comment]
After installing gradio in venv, the error `ModuleNotFoundError: No module named 'gradio'` disappeared.
So, when I executed `run_gui.ps1` again, I got the following new error.

`\layerdivider\venv\Lib\site-packages\gradio_client\documentation.py:103: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
\layerdivider\venv\Lib\site-packages\gradio_client\documentation.py:103: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")`
